### ISSUE TITLE
python: No matching distribution found for requirements.txt

### ISSUE THREAD

**Issue by yvz5** [kubeless/runtimes#52]
Hey there,

the dependency kafka-python is not installed.

error: from install container
```
/kubeless/requirements.txt: OK
WARNING: The directory '/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check
the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not find a version that satisfies the requirement requirements.txt (from -r /kubeless/requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for requirements.txt (from -r /kubeless/requirements.txt (line 1))
```

requirements.txt
```
kafka-python
```

function.yaml
```
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: python-demo
  namespace: kubeless
  labels:
    created-by: kubeless
    function: python-demo
spec:
  runtime: python3.7
  timeout: "180"
  handler: function.app
  deps: "requirements.txt"
  checksum: sha256:FUNCTION-CHECKSUM
  function: "FUNCTION-URL"
  function-content-type: url+zip
```
any ideas how to debug this ?

**Comment by andresmgot** [comment]
if your function YAML, `deps` should be the content of the requirements file (not the path to the file). In your case, it should be enough if you change:

```patch
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: python-demo
  namespace: kubeless
  labels:
    created-by: kubeless
    function: python-demo
spec:
  runtime: python3.7
  timeout: "180"
  handler: function.app
  deps: "kafka-python"
  checksum: sha256:FUNCTION-CHECKSUM
  function: "FUNCTION-URL"
  function-content-type: url+zip
```

**Comment by yvz5** [comment]
Thats not how we do it for node js. I wish you could change this to use the requirements file. how do I add multiple deps then ?

**Comment by andresmgot** [comment]
> Thats not how we do it for node js. I wish you could change this to use the requirements file.

It's the same for all the languages, right now, the only supported mode of adding a dep file is adding the dependencies there. When you execute `kubeless function deploy --dependencies requirements.txt ...` that file is read and encoded in the yaml.

> how do I add multiple deps then ?

You can do so like any other multi-line YAML value. For example:

```yaml
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: python-demo
  namespace: kubeless
  labels:
    created-by: kubeless
    function: python-demo
spec:
  runtime: python3.7
  timeout: "180"
  handler: function.app
  deps: |-
    kafka-python
    other-dependency
  checksum: sha256:FUNCTION-CHECKSUM
  function: "FUNCTION-URL"
  function-content-type: url+zip
```

In any case, if you are curious of how to generate a function YAML, you can always use the `kubeless` CLI to help you. It will print the YAML of a function if you use the flags `--dryrun -output yaml. For example:

```
kubeless function deploy post-python --runtime python2.7 --handler hellowithdata.handler --from-file examples/hellowithdata.py -o yaml --dryrun
```
